---

apiVersion: 'traefik.io/v1alpha1'
kind: 'Middleware'
metadata:
  name: 'secure-headers'
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    frameDeny: true
    stsSeconds: 31536
