---

apiVersion: 'cert-manager.io/v1'
kind: 'Certificate'
metadata:
  name: 'filebrowser-cert'
spec:
  commonName: '$W_FILEBROWSER_DOMAIN'
  secretName: 'secret-filebrowser-tls'
  dnsNames:
    - '$W_FILEBROWSER_DOMAIN'
  issuerRef:
    name: 'letsencrypt'
    kind: 'ClusterIssuer'
