---

apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'

resources:
  # Kubernetes Dashboard
  - 'https://raw.githubusercontent.com/kubernetes/dashboard/v2.5.0/aio/deploy/recommended.yaml'
  - 'users/admin.yaml'

  # Containers
  - 'deployments/homeassistant.yaml'
  - 'deployments/filebrowser.yaml'

  # Traefik
  - 'ingress/middleware.yaml'
  - 'ingress/local.yaml'
  # - 'ingress/public.yaml'


# patchesStrategicMerge:
  # - 'patches/volumes.yaml'

