---

apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'
namespace: 'andrut'

resources:
  - './namespace.yaml'
  - '../../base'

commonLabels:
  app: 'home-server'

# patches:
#   - path: './allocation.yaml'
#   - path: './auth.yaml'
#   - path: './ingress.yaml'
#   - path: './volumes.yaml'
