---

apiVersion: 'cert-manager.io/v1'
kind: 'ClusterIssuer'
metadata:
  name: 'letsencrypt'
spec:
  acme:
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    email: 'john@example.org'
    privateKeySecretRef:
      name: 'letsencrypt'
    solvers:
      - http01:
          ingress:
            class: 'traefik'
---

apiVersion: 'cert-manager.io/v1'
kind: 'Certificate'
metadata:
  name: 'ingress-cert'
  namespace: 'default'
spec:
  commonName: 'yourdomain.com'
  secretName: 'ingress-secret' 
  dnsNames:
    - 'yourdomain.com'
  issuerRef:
    name: 'letsencrypt'
    kind: 'ClusterIssuer'
