default_config:

# This allows us to access home assistant through our ingress controller  
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - '10.0.0.0/8'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
