---

apiVersion: 'traefik.io/v1alpha1'
kind: 'IngressRoute'
metadata:
  name: 'main-ingress'
spec:
  entryPoints:
    - 'web'
  routes:
    - kind: 'Rule'
      match: Host(`andrut`)
      services:
        - name: 'flame'
          port: 5005
    - kind: 'Rule'
      match: Host(`andrut`) && PathPrefix(`/whoami`)
      services:
        - name: 'whoami'
          port: 80
    - kind: 'Rule'
      match: Host(`andrut`) &&  PathPrefix(`/transmission`)
      services:
        - name: 'transmission'
          port: 9091

    # Traefik Dashboard
    - match: Host(`andrut`) && PathPrefix(`/traefik/`)
      kind: 'Rule'
      services:
        - name: 'api@internal'
          kind: 'TraefikService'
      middlewares:
        - name: 'traefik-path'
    - match: PathPrefix(`/api`) && HeadersRegexp(`Referer`, `.*/traefik/.*`)
      kind: 'Rule'
      services:
        - name: 'api@internal'
          kind: 'TraefikService'
