---

apiVersion: 'traefik.io/v1alpha1'
kind: 'IngressRoute'
metadata:
  name: 'main-ingress'
spec:
  entryPoints:
    - 'web'
  routes:
    - kind: 'Rule'
      match: Host(`waffle`)
      services:
        - name: 'flame'
          port: 5005
    - kind: 'Rule'
      match: Host(`waffle`) && PathPrefix(`/whoami`)
      services:
        - name: 'whoami'
          port: 80
    - kind: 'Rule'
      match: Host(`waffle`) && PathPrefix(`/jackett`)
      services:
        - name: 'jackett'
          port: 9117
    - kind: 'Rule'
      match: Host(`waffle`) && PathPrefix(`/bazarr`)
      services:
        - name: 'bazarr'
          port: 6767
    - kind: 'Rule'
      match: Host(`waffle`) && PathPrefix(`/radarr`)
      services:
        - name: 'radarr'
          port: 7878
    - kind: 'Rule'
      match: Host(`waffle`) && PathPrefix(`/sonarr`)
      services:
        - name: 'sonarr'
          port: 8989
    - kind: 'Rule'
      match: Host(`waffle`) &&  PathPrefix(`/transmission`)
      services:
        - name: 'transmission'
          port: 9091

    # Traefik Dashboard
    - match: Host(`waffle`) && PathPrefix(`/traefik/`)
      kind: 'Rule'
      services:
        - name: 'api@internal'
          kind: 'TraefikService'
      middlewares:
        - name: 'traefik-path'
    - match: PathPrefix(`/api`) && HeadersRegexp(`Referer`, `.*/traefik/.*`)
      kind: 'Rule'
      services:
        - name: 'api@internal'
          kind: 'TraefikService'
