---

apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'sonarr'
  labels:
    app: 'sonarr'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'sonarr'
  template:
    metadata:
      labels:
        app: 'sonarr'
    spec:
      containers:
        - name: 'sonarr'
          image: 'linuxserver/sonarr:arm32v7-3.0.9'
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 8989
              protocol: 'TCP'
          volumeMounts:
            - mountPath: '/config'
              name: 'sonarr-config'
            - mountPath: '/downloads'
              name: 'sonarr-downloads'
            - mountPath: '/tv'
              name: 'sonarr-tv'
      volumes:
        - name: 'sonarr-config'
          nfs:
            server: '3bp-waits'
            path: '/srv/config/sonarr'
        - name: 'sonarr-downloads'
          nfs:
            server: '3bp-waits'
            path: '/srv/downloads'
        - name: 'sonarr-tv'
          nfs:
            server: '3bp-waits'
            path: '/srv/media/television'
      nodeName: '3bp-waits'

---

apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'sonarr'
  labels:
    app: 'sonarr'
spec:
  ports:
    - port: 8989
      protocol: 'TCP'
      targetPort: 8989
  selector:
    app: 'sonarr'
