---

apiVersion: 'cert-manager.io/v1'
kind: 'ClusterIssuer'
metadata:
  name: 'letsencrypt'
spec:
  acme:
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    email: 'josh.walwyn@gmail.com'
    privateKeySecretRef:
      name: 'letsencrypt'
    solvers:
      - http01:
          ingress:
            class: 'traefik'

---

apiVersion: 'cert-manager.io/v1'
kind: 'Certificate'
metadata:
  name: 'filebrowser-cert'
  namespace: 'default'
spec:
  commonName: 'f.shw.al'
  secretName: 'filebrowser-tls-secret'
  dnsNames:
    - 'f.shw.al'
  issuerRef:
    name: 'letsencrypt'
    kind: 'ClusterIssuer'

---

apiVersion: 'cert-manager.io/v1'
kind: 'Certificate'
metadata:
  name: 'homeassistant-cert'
  namespace: 'default'
spec:
  commonName: 'h.shw.al'
  secretName: 'homeassistant-tls-secret'
  dnsNames:
    - 'h.shw.al'
  issuerRef:
    name: 'letsencrypt'
    kind: 'ClusterIssuer'

---

apiVersion: 'cert-manager.io/v1'
kind: 'Certificate'
metadata:
  name: 'waffle-cert'
  namespace: 'default'
spec:
  commonName: 'z.shw.al'
  secretName: 'waffle-tls-secret'
  dnsNames:
    - 'z.shw.al'
  issuerRef:
    name: 'letsencrypt'
    kind: 'ClusterIssuer'
