---

apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'filebrowser'
  labels:
    app: 'filebrowser'
spec:
  selector:
    matchLabels:
      app: 'filebrowser'
  template:
    metadata:
      labels:
        app: 'filebrowser'
    spec:
      containers:
        - name: 'filebrowser'
          image: 'filebrowser/filebrowser'
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 80
              protocol: 'TCP'
          livenessProbe:
            httpGet:
              port: 80
              path: '/health'
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            terminationGracePeriodSeconds: 30

---

apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'filebrowser'
  labels:
    app: 'filebrowser'
spec:
  ports:
    - port: 80
      protocol: 'TCP'
      targetPort: 80
  selector:
    app: 'filebrowser'
