---

apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'sonarr'
  labels:
    app: 'sonarr'
spec:
  selector:
    matchLabels:
      app: 'sonarr'
  template:
    metadata:
      labels:
        app: 'sonarr'
    spec:
      containers:
        - name: 'sonarr'
          image: 'linuxserver/sonarr'
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 8989
              protocol: 'TCP'
          volumeMounts:
            - mountPath: '/config'
              name: 'sonarr-config'
            - mountPath: '/downloads'
              name: 'sonarr-downloads'
            - mountPath: '/tv'
              name: 'sonarr-tv'
          livenessProbe:
            httpGet:
              port: 8989
              path: '/sonarr'
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            terminationGracePeriodSeconds: 30
      volumes:
        - name: 'sonarr-config'
          emptyDir: {}
        - name: 'sonarr-downloads'
          emptyDir: {}
        - name: 'sonarr-tv'
          emptyDir: {}

---

apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'sonarr'
  labels:
    app: 'sonarr'
spec:
  ports:
    - port: 8989
      protocol: 'TCP'
      targetPort: 8989
  selector:
    app: 'sonarr'
