---

apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'whoami'
  labels:
    app: 'whoami'
spec:
  selector:
    matchLabels:
      app: 'whoami'
  template:
    metadata:
      labels:
        app: 'whoami'
    spec:
      containers:
        - name: 'whoami'
          image: 'containous/whoami'
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 80
              protocol: 'TCP'

---

apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'whoami'
  labels:
    app: 'whoami'
spec:
  ports:
    - port: 80
      protocol: 'TCP'
      targetPort: 80
  selector:
    app: 'whoami'
