---

apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'

configurations:
  - './configurations/nameReference.yaml'

resources:
  # Deployments and Services
  - './deployments/filebrowser.yaml'
  - './deployments/flame.yaml'
  - './deployments/homeassistant.yaml'
  - './deployments/transmission.yaml'
  - './deployments/whoami.yaml'

  # Ingress - Middlewares
  - './ingress/middlewares/traefik-path.yaml'
  - './ingress/middlewares/secure-headers.yaml'

  # Ingress - Routes
  - './ingress/filebrowser.yaml'
  - './ingress/homeassistant.yaml'
  - './ingress/main.yaml'
