---

apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'

namespace: 'andrut'

configurations:
  - './configurations/nameReference.yaml'

resources:
  - '../../base'
  - './namespace.yaml'
